query comments($postId: Int!) {
  post(postId: $postId) {
    comments {
      id
      content
      updatedAt
      user {
        username
      }
    }
  }
}

mutation addComment($postId: Int!, $commentInput: CommentInput!) {
  addComment(postId: $postId, commentInput: $commentInput) {
    id
  }
}
