fragment postFragment on Post {
  id
  title
  content
  community {
    id
    name
  }
  commentsCount
  author {
    username
  }
}

query posts($title: String, $communityId: Int, $authorId: Int) {
  posts(title: $title, communityId: $communityId, authorId: $authorId) {
    ...postFragment
  }
}

query ourPosts($title: String, $communityId: Int) {
  ourPosts(title: $title, communityId: $communityId) {
    ...postFragment
  }
}

query post($postId: Int!) {
  post(postId: $postId) {
    ...postFragment
    updatedAt
  }
}

mutation createPost($createPostInput: CreatePostInput!) {
  createPost(createPostInput: $createPostInput) {
    id
  }
}

mutation updatePost($postId: Int!, $updatePostInput: UpdatePostInput!) {
  updatePost(postId: $postId, updatePostInput: $updatePostInput) {
    id
  }
}

mutation deletePost($postId: Int!) {
  deletePost(postId: $postId) {
    id
  }
}
